setting:
  additionalInfo: False


imageType:
  Original: { }

featureClass:
  firstorder:
    - 'Energy'
    - 'TotalEnergy'
    - 'Entropy'
    - 'Minimum'
    - '10Percentile'
    - '90Percentile'
    - 'Maximum'
    - 'Mean'
    - 'Median'
    - 'InterquartileRange'
    - 'Range'
    - 'MeanAbsoluteDeviation'
    - 'RobustMeanAbsoluteDeviation'
    - 'RootMeanSquared'
    - 'Skewness'
    - 'Kurtosis'
    - 'Variance'
    - 'Uniformity'
  glcm:
    - 'Autocorrelation'
    - 'JointAverage'
    - 'ClusterProminence'
    - 'ClusterShade'
    - 'ClusterTendency'
    - 'Contrast'
    - 'Correlation'
    - 'DifferenceAverage'
    - 'DifferenceEntropy'
    - 'DifferenceVariance'
    - 'JointEnergy'
    - 'JointEntropy'
    - 'Imc1'
    - 'Imc2'
    - 'Idm'
    - 'MCC'
    - 'Idmn'
    - 'Id'
    - 'Idn'
    - 'InverseVariance'
    - 'MaximumProbability'
    - 'SumEntropy'
    - 'SumSquares'
  glrlm:
    - 'ShortRunEmphasis'
    - 'LongRunEmphasis'
    - 'GrayLevelNonUniformity'
    - 'GrayLevelNonUniformityNormalized'
    - 'RunLengthNonUniformity'
    - 'RunLengthNonUniformityNormalized'
    - 'RunPercentage'
    - 'GrayLevelVariance'
    - 'RunVariance'
    - 'RunEntropy'
    - 'LowGrayLevelRunEmphasis'
    - 'HighGrayLevelRunEmphasis'
    - 'ShortRunLowGrayLevelEmphasis'
    - 'ShortRunHighGrayLevelEmphasis'
    - 'LongRunLowGrayLevelEmphasis'
    - 'LongRunHighGrayLevelEmphasis'
  glszm:
    - 'SmallAreaEmphasis'
    - 'LargeAreaEmphasis'
    - 'GrayLevelNonUniformity'
    - 'GrayLevelNonUniformityNormalized'
    - 'SizeZoneNonUniformity'
    - 'SizeZoneNonUniformityNormalized'
    - 'ZonePercentage'
    - 'GrayLevelVariance'
    - 'ZoneVariance'
    - 'ZoneEntropy'
    - 'LowGrayLevelZoneEmphasis'
    - 'HighGrayLevelZoneEmphasis'
    - 'SmallAreaLowGrayLevelEmphasis'
    - 'SmallAreaHighGrayLevelEmphasis'
    - 'LargeAreaLowGrayLevelEmphasis'
    - 'LargeAreaHighGrayLevelEmphasis'
  ngtdm:
    - 'Coarseness'
    - 'Contrast'
    - 'Busyness'
    - 'Complexity'
    - 'Strength'
  gldm:
    - 'SmallDependenceEmphasis'
    - 'LargeDependenceEmphasis'
    - 'GrayLevelNonUniformity'
    - 'DependenceNonUniformity'
    - 'DependenceNonUniformityNormalized'
    - 'GrayLevelVariance'
    - 'DependenceVariance'
    - 'DependenceEntropy'
    - 'LowGrayLevelEmphasis'
    - 'HighGrayLevelEmphasis'
    - 'SmallDependenceLowGrayLevelEmphasis'
    - 'SmallDependenceHighGrayLevelEmphasis'
    - 'LargeDependenceLowGrayLevelEmphasis'
    - 'LargeDependenceHighGrayLevelEmphasis'